version: '3.9'
services:
  db:
    image: postgres:alpine3.17
    restart: always
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PWD}
      - POSTGRES_DB=${PG_DB}
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/postgresql/data      
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:6.20
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGA_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGA_PWD}
    volumes:
      - type: volume
        source: pgadmin_data
        target: /var/lib/pgadmin
    ports:
      - 5050:80

  grafana:
    image: grafana/grafana-oss:9.4.3
    restart: always
    volumes:
      - type: volume
        source: grafana_data
        target: /var/lib/grafana
    ports:
      - 3000:3000

  app-dev:
    image: dashbuild-dev
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5173:5173
      
volumes:
  db_data:
  pgadmin_data:
  grafana_data:
