version: '3.9'
services:
  grafana:
    image: grafana/grafana-oss:9.4.3
    restart: always
    volumes:
      - type: volume
        source: grafana_data
        target: /var/lib/grafana
    ports:
      - 3000:3000

volumes:
  grafana_data:


