version: '3.9'
services:
  postgres:
    image: postgres:alpine3.17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dashbuild
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/postgresql/data
    ports:
      - 5432:5432

  grafana:
    image: grafana/grafana-oss:9.4.3
    restart: always
    volumes:
      - type: volume
        source: grafana_data
        target: /var/lib/grafana
    ports:
      - 3000:3000
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug

  grafana_image_renderer:
    platform: linux/amd64
    image: grafana/grafana-image-renderer:latest
    ports:
      - 8081:8081
    depends_on:
      - grafana

  panel_interpreter:
    build: ./panel_interpreter
    restart: always
    ports:
      - 8000:8000

  app:
    build: ./app
    restart: always
    ports:
      - 80:80
    depends_on:
      - postgres
      - grafana
      - grafana_image_renderer

volumes:
  db_data:
  pgadmin_data:
  grafana_data:


