version: '3.9'
services:
  db:
    image: postgres:alpine3.17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dashbuild
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/postgresql/data      
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:6.20
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - type: volume
        source: pgadmin_data
        target: /var/lib/pgadmin
    ports:
      - 5050:80

  grafana:
    image: grafana/grafana-oss:9.4.3
    restart: always
    volumes:
      - type: volume
        source: grafana_data
        target: /var/lib/grafana
    ports:
      - 3000:3000
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug

  renderer:
    platform: linux/amd64
    image: grafana/grafana-image-renderer:latest
    ports:
      - 8081

volumes:
  db_data:
  pgadmin_data:
  grafana_data:
